<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_3,543</name>
   <tag></tag>
   <elementGuidId>4ae9cb4c-bf6f-4dfd-ac66-6d61b0a94c67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.yt-simple-endpoint.style-scope.ytd-toggle-button-renderer > #text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[70]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>56f46141-5f4d-4ef8-b361-9a54535ad71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a45f9b0-a55b-4171-99cc-e751921d055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-toggle-button-renderer style-text</value>
      <webElementGuid>b6701584-fd30-49b3-9e0e-63b29fe8e7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>3,543 “Me gusta”</value>
      <webElementGuid>42cf1ca1-a4e7-4a5e-bc4d-d5bddb0fe916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3,543</value>
      <webElementGuid>aff23200-de6e-4354-b354-f36120841b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-container&quot;)/div[@id=&quot;menu&quot;]/ytd-menu-renderer[@class=&quot;style-scope ytd-video-primary-info-renderer&quot;]/div[@id=&quot;top-level-buttons-computed&quot;]/ytd-toggle-button-renderer[@class=&quot;style-scope ytd-menu-renderer force-icon-button style-text&quot;]/a[@class=&quot;yt-simple-endpoint style-scope ytd-toggle-button-renderer&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>b59caaa2-d03e-4d42-af79-064eed0f625c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[70]</value>
      <webElementGuid>6d92733d-0bc2-4b5f-ad28-656cc39f6b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-level-buttons-computed']/ytd-toggle-button-renderer/a/yt-formatted-string</value>
      <webElementGuid>1a086952-3c76-4a9a-91d9-aadd329fd994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANA ÉXITOS SUS MeJores CancioNES 30 SUPER ÉxiTOS RomántiCAS INOLVIDABLES MIX'])[2]/following::yt-formatted-string[2]</value>
      <webElementGuid>2b67ab0a-82c7-4c2f-a02f-79009c974bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desplázate hacia abajo para obtener más información'])[1]/following::yt-formatted-string[4]</value>
      <webElementGuid>883e8078-62c7-48ba-9310-12ff9475e7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No me gusta'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>1bca8946-1f1f-4642-aeba-f37acf349890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3,543']/parent::*</value>
      <webElementGuid>150ddaaf-5dac-4773-ab0e-850c3374d3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-toggle-button-renderer/a/yt-formatted-string</value>
      <webElementGuid>b77d5c95-b64d-453a-9293-cb4c7dd55298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and (text() = '3,543' or . = '3,543')]</value>
      <webElementGuid>539e50ca-2b8d-4743-a998-d36d99d3b92a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
